### ISSUE TITLE
PC4 Challenges and Solutions

### ISSUE THREAD

**Issue by psmitty7373** [cisagov/prescup-challenges#16]
# 💡 Summary # PC4 Challenges and Solutions

Please add the PC4 solutions and challenges for all rounds to the repository.

**Comment by sei-mkaar** [comment]
@psmitty7373 We're on it. We're aiming to have the PC4 solutions posted by the end of January. Other open source artifacts will follow at a later date.

**Comment by jacobtvpuckett** [comment]
I am trying to download the VMs to do last years challenges and am getting hung up by the packer application with "waiting for winrm" 
Does anybody know a solution or workaround for this issue?
