### ISSUE TITLE
Packer hanging up on "waiting for winrm"

### ISSUE THREAD

**Issue by jacobtvpuckett** [cisagov/prescup-challenges#24]
# 🐛 Summary #

I followed the directions to get the VMs going for the previous years challenges (downloading packer/virtualbox) and when I am trying to build the VM, packer gets hung up on "waiting for winrm"

It sits for about 4 hours then timesout, and destroys the vms.

Any solutions or workarounds for this issue?

**Comment by ColtonCISA** [comment]
Closing issue as resolved.
